# Github Action to create a release
name: Create Release

on:
  push:
    branches:
      - 'main'
    paths:
      - version.txt

jobs:
  release:
    if: ${{ github.repository == 'notSoWiseOldMan/eks-pod-identity-agent' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Tag release
        run: |
          /usr/bin/git config --global user.email actions@github.com
          /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
          hack/tag-release.sh
      - name: Trigger Image Publish
        run: |
          VERSION=$(cat version.txt);
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }} " \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/notSoWiseOldMan/eks-pod-identity-agent/actions/workflows/publish.yaml/dispatches \
            -d '{"ref":"main","inputs":{"IMAGE_TAG":"$VERSION"}}'
